"""Add S3 storage fields to MCP registry tables

Revision ID: 0ab9c2560c80
Revises: 562139430c84
Create Date: 2025-11-05 13:57:40.418955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab9c2560c80'
down_revision: Union[str, Sequence[str], None] = '562139430c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_registry', sa.Column('s3_bucket', sa.String(length=255), nullable=True))
    op.add_column('mcp_registry', sa.Column('s3_key', sa.Text(), nullable=True))
    op.add_column('mcp_versions', sa.Column('s3_bucket', sa.String(length=255), nullable=True))
    op.add_column('mcp_versions', sa.Column('s3_key', sa.Text(), nullable=True))
    op.add_column('mcp_versions', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_versions', 'file_size')
    op.drop_column('mcp_versions', 's3_key')
    op.drop_column('mcp_versions', 's3_bucket')
    op.drop_column('mcp_registry', 's3_key')
    op.drop_column('mcp_registry', 's3_bucket')
    # ### end Alembic commands ###
