"""add_reasoning_level_to_ai_responses

Revision ID: 2eed3a00a469
Revises: 616f4394f301
Create Date: 2025-10-11 12:28:07.607781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eed3a00a469'
down_revision: Union[str, Sequence[str], None] = '616f4394f301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('reasoning_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_responses', 'reasoning_level')
    # ### end Alembic commands ###
