"""add_is_agent_mode_and_device_id_to_tables

Revision ID: 616f4394f301
Revises: fb77c9c3fb35
Create Date: 2025-10-09 11:40:24.485066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616f4394f301'
down_revision: Union[str, Sequence[str], None] = 'fb77c9c3fb35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_agent_mode as nullable first, then set default and make it NOT NULL
    op.add_column('ai_responses', sa.Column('is_agent_mode', sa.Boolean(), nullable=True))
    op.execute("UPDATE ai_responses SET is_agent_mode = false WHERE is_agent_mode IS NULL")
    op.alter_column('ai_responses', 'is_agent_mode', nullable=False)
    
    op.add_column('ai_responses', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('user_messages', sa.Column('device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_messages', 'device_id')
    op.drop_column('ai_responses', 'device_id')
    op.drop_column('ai_responses', 'is_agent_mode')
    # ### end Alembic commands ###
