"""model tracking for chats

Revision ID: 73ad13192b51
Revises: adee8c657e45
Create Date: 2025-09-10 14:35:29.878181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ad13192b51'
down_revision: Union[str, Sequence[str], None] = 'adee8c657e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values first to handle existing data
    op.add_column('ai_responses', sa.Column('model_used', sa.String(length=255), nullable=False, server_default='gpt-4.1-2025-04-14'))
    op.add_column('user_messages', sa.Column('model_requested', sa.String(length=255), nullable=False, server_default='gpt-4.1-2025-04-14'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_messages', 'model_requested')
    op.drop_column('ai_responses', 'model_used')
    # ### end Alembic commands ###
