"""Add MCP registry tables

Revision ID: 778d05308e99
Revises: 2eed3a00a469
Create Date: 2025-10-15 08:54:05.914704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '778d05308e99'
down_revision: Union[str, Sequence[str], None] = '2eed3a00a469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_registry',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('latest_version', sa.String(length=20), nullable=False),
    sa.Column('min_app_version', sa.String(length=20), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_mcp_active', 'mcp_registry', ['is_active'], unique=False)
    op.create_index('idx_mcp_category', 'mcp_registry', ['category'], unique=False)
    op.create_index(op.f('ix_mcp_registry_id'), 'mcp_registry', ['id'], unique=False)
    op.create_table('mcp_versions',
    sa.Column('mcp_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mcp_id'], ['mcp_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_version_unique', 'mcp_versions', ['mcp_id', 'version'], unique=True)
    op.create_index('idx_mcp_versions_mcp_id', 'mcp_versions', ['mcp_id'], unique=False)
    op.create_index(op.f('ix_mcp_versions_id'), 'mcp_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_versions_id'), table_name='mcp_versions')
    op.drop_index('idx_mcp_versions_mcp_id', table_name='mcp_versions')
    op.drop_index('idx_mcp_version_unique', table_name='mcp_versions')
    op.drop_table('mcp_versions')
    op.drop_index(op.f('ix_mcp_registry_id'), table_name='mcp_registry')
    op.drop_index('idx_mcp_category', table_name='mcp_registry')
    op.drop_index('idx_mcp_active', table_name='mcp_registry')
    op.drop_table('mcp_registry')
    # ### end Alembic commands ###
