"""Add RocPortal Status Column

Revision ID: 7bf38ae931f7
Revises: fb87297cde8a
Create Date: 2025-08-22 16:27:40.558972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf38ae931f7'
down_revision: Union[str, Sequence[str], None] = 'fb87297cde8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('rocportal_status', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'rocportal_status')
    # ### end Alembic commands ###
