"""add media_links column to ai_responses

Revision ID: adee8c657e45
Revises: e9b49a691e1c
Create Date: 2025-08-27 12:47:46.256459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adee8c657e45'
down_revision: Union[str, Sequence[str], None] = 'e9b49a691e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('media_links', postgresql.JSONB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_responses', 'media_links')
    # ### end Alembic commands ###
