"""Add agent_mode_opt_in to user_settings and create history table

Revision ID: ca31fa1da13a
Revises: c2d3e4f5a6b7
Create Date: 2026-01-20 10:42:58.231166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ca31fa1da13a'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_mode_opt_in_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opt_in_status', sa.Boolean(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_mode_opt_in_history_changed_at', 'agent_mode_opt_in_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_agent_mode_opt_in_history_id'), 'agent_mode_opt_in_history', ['id'], unique=False)
    op.create_index('ix_agent_mode_opt_in_history_user_id', 'agent_mode_opt_in_history', ['user_id'], unique=False)
    op.add_column('user_settings', sa.Column('agent_mode_opt_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'agent_mode_opt_in')
    op.drop_index('ix_agent_mode_opt_in_history_user_id', table_name='agent_mode_opt_in_history')
    op.drop_index(op.f('ix_agent_mode_opt_in_history_id'), table_name='agent_mode_opt_in_history')
    op.drop_index('ix_agent_mode_opt_in_history_changed_at', table_name='agent_mode_opt_in_history')
    op.drop_table('agent_mode_opt_in_history')
    # ### end Alembic commands ###
