"""Seperated chat message table into a user and AI message table

Revision ID: e9b49a691e1c
Revises: 9751384d7f4e
Create Date: 2025-08-26 17:22:20.053373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b49a691e1c'
down_revision: Union[str, Sequence[str], None] = '9751384d7f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get reference to existing messagestatus enum (created in previous migration)
    messagestatus_enum = postgresql.ENUM('SUBMITTED', 'STREAMING', 'COMPLETED', 'ERRORED', name='messagestatus', create_type=False)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', messagestatus_enum, nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=True),
    sa.Column('client_temp_id', sa.String(length=36), nullable=True),
    sa.Column('sources_requested', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_user_messages_id'), 'user_messages', ['id'], unique=False)
    op.create_table('ai_responses',
    sa.Column('user_message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', messagestatus_enum, nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('sources_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['user_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_responses_id'), 'ai_responses', ['id'], unique=False)
    
    # Update message_feedback table FIRST (before dropping chat_messages)
    op.add_column('message_feedback', sa.Column('ai_response_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('message_feedback_message_id_fkey'), 'message_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'message_feedback', 'ai_responses', ['ai_response_id'], ['id'], ondelete='SET NULL')
    op.drop_column('message_feedback', 'message_id')
    
    # NOW we can safely drop chat_messages table
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_feedback', sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('message_feedback_message_id_fkey'), 'message_feedback', 'chat_messages', ['message_id'], ['id'], ondelete='SET NULL')
    op.drop_column('message_feedback', 'ai_response_id')
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_user_message', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sources_used', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SUBMITTED', 'STREAMING', 'COMPLETED', 'ERRORED', name='messagestatus'), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('client_temp_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('chat_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_messages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_chat_messages_idempotency_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_ai_responses_id'), table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index(op.f('ix_user_messages_id'), table_name='user_messages')
    op.drop_table('user_messages')
    # ### end Alembic commands ###
