"""Add rocscience version compatibility fields to mcp_registry

Revision ID: f0f638995182
Revises: e280c9019ae0
Create Date: 2025-12-16 15:11:21.800167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0f638995182'
down_revision: Union[str, Sequence[str], None] = 'e280c9019ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_registry', sa.Column('rocscience_app', sa.String(length=50), nullable=True))
    op.add_column('mcp_registry', sa.Column('required_app_version', sa.String(length=20), nullable=True))
    op.add_column('mcp_registry', sa.Column('rocscience_app_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_registry', 'rocscience_app_path')
    op.drop_column('mcp_registry', 'required_app_version')
    op.drop_column('mcp_registry', 'rocscience_app')
    # ### end Alembic commands ###
